{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cloudmaven.fullname" . }}-api-healthcheck
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: healthcheck
              image: curlimages/curl:8.8.0
              args:
                - "-fsS"
                - "http://{{ include "cloudmaven.fullname" . }}-backend:{{ .Values.backend.port }}/health"
{{- end }}

