apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudmaven.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: {{ include "cloudmaven.name" . }}
spec:
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: {{ include "cloudmaven.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: http

